# Generated by Django 4.1.7 on 2023-09-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisements',
        ),
    ]
